version: '3'
services:
  todo-backend:
    build: '.'
    container_name: todo-backend
    depends_on:
      - todo-db
    environment:
      - DB_URL=postgres://root:password@todo-db/db?charset=UTF8
    ports:
      - '6969:6969'
    volumes:
      - .:/opt/app

  todo-db:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    image: postgres:11
    ports:
      - 0.0.0.0:7200:5432
